language: node_js
node_js:
  - 12
  - 10
  - 8
cache: yarn
install:
  - yarn install
  - yarn link
  - cd example
  - yarn link react-particles-webgl
  - yarn install
script:
  - yarn test
  - yarn build
branches:
  only: master
notifications:
  email: false
